### ISSUE TITLE
Generic error page when looking at Oracle.ManagedDataAccess

### ISSUE THREAD

**Issue by ascott18** [praeclarum/FuGetGallery#107]
https://www.fuget.org/packages/Oracle.ManagedDataAccess

![image](https://user-images.githubusercontent.com/5017521/77786693-781fcf80-701b-11ea-859d-f638185b5842.png)

**Comment by MaceWindu** [comment]
See #103

**Comment by praeclarum** [comment]
Looks like this is fixed? Please re-open if not.

**Comment by MaceWindu** [comment]
It works for recent releases, but fails e.g. for this one
https://www.fuget.org/packages/Oracle.ManagedDataAccess/19.9.0/lib/net40/Oracle.ManagedDataAccess.dll/OracleInternal.Common

**Comment by bgrainger** [comment]
```
fail: Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware[1]
      An unhandled exception has occurred while executing the request.
System.NullReferenceException: Object reference not set to an instance of an object.
   at FuGetGallery.Pages.packages.Pages_packages_details.ExecuteAsync() in C:\FuGetGallery\Pages\packages\details.cshtml:line 405
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
```
