### ISSUE TITLE
Error reading package when there are only pre-release versions

### ISSUE THREAD

**Issue by bgrainger** [praeclarum/FuGetGallery#131]
Open the fuget page for a package that _only_ has pre-release versions:

* https://www.fuget.org/packages/Southport.Messaging.Phone.Twilio/
* https://www.fuget.org/packages/PinMame.Native.linux-x64/
* https://www.fuget.org/packages/Test.Xam.Prerelease/

You receive the following error:

```
Error reading package
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FuGetGallery.PackageData.Read(MemoryStream bytes, HttpClient httpClient) in D:\home\site\repository\Data\PackageData.cs:line 118
   at FuGetGallery.PackageData.PackageDataCache.<>c__DisplayClass2_0.<ReadPackageFromUrl>b__0() in D:\home\site\repository\Data\PackageData.cs:line 412
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at FuGetGallery.PackageData.PackageDataCache.ReadPackageFromUrl(PackageData package, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 412
   at FuGetGallery.PackageData.PackageDataCache.GetValueAsync(String arg0, PackageVersion arg1, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 385
```

The version badge also appears to be incorrect (it says `v0`) but that may be a side-effect of this bug.

![image](https://user-images.githubusercontent.com/188129/107823915-70514280-6d35-11eb-9c25-9abc796ae923.png)

**Comment by bgrainger** [comment]
This may be a duplicate of https://github.com/praeclarum/FuGetGallery/issues/118.
