### ISSUE TITLE
Error when reading some packages 

### ISSUE THREAD

**Issue by NickName73** [praeclarum/FuGetGallery#160]
Error when reading NiTiSCore
![image](https://user-images.githubusercontent.com/60577131/146668160-d7580417-12a6-4fc9-b28e-1aa4d0a85b85.png)

Full error message:

```
System.InvalidOperationException: The given header was not found.
   at System.Net.Http.Headers.HttpHeaders.GetValues(HeaderDescriptor descriptor)
   at FuGetGallery.PackageData.ReadEntriesAsync(HttpClient client, String file)
   at FuGetGallery.PackageData.ReadAsync(HttpClient httpClient, String packageUri) in /home/runner/work/FuGetGallery/FuGetGallery/Data/PackageData.cs:line 303
   at FuGetGallery.PackageData.PackageDataCache.ReadPackageFromUrl(PackageData package, HttpClient httpClient, CancellationToken token) in /home/runner/work/FuGetGallery/FuGetGallery/Data/PackageData.cs:line 600
   at FuGetGallery.PackageData.PackageDataCache.GetValueAsync(String arg0, PackageVersion arg1, HttpClient httpClient, CancellationToken token) in /home/runner/work/FuGetGallery/FuGetGallery/Data/PackageData.cs:line 576
```

**Comment by bgrainger** [comment]
Works OK for me:

![image](https://user-images.githubusercontent.com/188129/146995776-815385db-b820-4992-92e3-dfa58fba3164.png)

Maybe a transient error?
