### ISSUE TITLE
Error reading package

### ISSUE THREAD

**Issue by thomaslevesque** [praeclarum/FuGetGallery#55]
I tried to access the FuGet page for a new package before it was validated on the NuGet gallery. Understandably, it produced an error:

> **Error reading package**
> System.IO.InvalidDataException: End of Central Directory record could not be found.
>    at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
>    at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
>    at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
>    at FuGetGallery.PackageData.Read(MemoryStream bytes, HttpClient httpClient) in D:\home\site\repository\Data\PackageData.cs:line 116
>    at FuGetGallery.PackageData.PackageDataCache.<>c__DisplayClass1_1.<GetValueAsync>b__0() in D:\home\site\repository\Data\PackageData.cs:line 379
>    at System.Threading.Tasks.Task.InnerInvoke()
>    at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
>    at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
> --- End of stack trace from previous location where exception was thrown ---
>    at FuGetGallery.PackageData.PackageDataCache.GetValueAsync(String arg0, PackageVersion arg1, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 379

But now the package is validated and indexed on NuGet, and I'm still seeing the same error... Could this be due to some kind of cache?

**Comment by thomaslevesque** [comment]
It looks like the cache [keeps the error](https://github.com/praeclarum/FuGetGallery/blob/374e87da6fd0531f7a00ab29f50099383587234c/Data/PackageData.cs#L386) and doesn't try again for another [365 days](https://github.com/praeclarum/FuGetGallery/blob/374e87da6fd0531f7a00ab29f50099383587234c/Data/PackageData.cs#L354)... Is there a way around this? (of course, since it's a memory cache, I guess it will be reset the next time you redeploy)

**Comment by svick** [comment]
I saw the same error on [the System.Linq.Async package](https://www.fuget.org/packages/System.Linq.Async).

**Comment by lachlanwgordon** [comment]
Hi friends,
Looks like I'm seeing the same issues with my new library [SQLiteAppTools](https://www.fuget.org/packages/SQLiteAppTools). It's been up on nuget for a couple of weeks now but I tried to look at in on FuGet immediately after publishing.

Did anyone find an issue other than waiting for 365 days/reset?

**Comment by wcoder** [comment]
The same error this [Xamarin.CommunityToolkit](https://www.fuget.org/packages/Xamarin.CommunityToolkit) package:

```
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FuGetGallery.PackageData.Read(MemoryStream bytes, HttpClient httpClient) in D:\home\site\repository\Data\PackageData.cs:line 118
   at FuGetGallery.PackageData.PackageDataCache.<>c__DisplayClass2_0.<ReadPackageFromUrl>b__0() in D:\home\site\repository\Data\PackageData.cs:line 412
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__278_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at FuGetGallery.PackageData.PackageDataCache.ReadPackageFromUrl(PackageData package, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 412
   at FuGetGallery.PackageData.PackageDataCache.GetValueAsync(String arg0, PackageVersion arg1, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 385
```
<img width="842" alt="Screen Shot 2020-11-12 at 6 08 00 PM" src="https://user-images.githubusercontent.com/766193/98957265-0a74d500-2512-11eb-8eec-48a28dade2e7.png">
