### ISSUE TITLE
Error displaying Microsoft.Extensions.Logging.Log4Net.AspNetCore

### ISSUE THREAD

**Issue by bgrainger** [praeclarum/FuGetGallery#98]
At https://www.fuget.org/packages/Microsoft.Extensions.Logging.Log4Net.AspNetCore/ no package details are displayed; only this error message:

## Error reading package

```
System.IO.InvalidDataException: End of Central Directory record could not be found.
   at System.IO.Compression.ZipArchive.ReadEndOfCentralDirectory()
   at System.IO.Compression.ZipArchive.Init(Stream stream, ZipArchiveMode mode, Boolean leaveOpen)
   at System.IO.Compression.ZipArchive..ctor(Stream stream, ZipArchiveMode mode, Boolean leaveOpen, Encoding entryNameEncoding)
   at FuGetGallery.PackageData.Read(MemoryStream bytes, HttpClient httpClient) in D:\home\site\repository\Data\PackageData.cs:line 118
   at FuGetGallery.PackageData.PackageDataCache.<>c__DisplayClass2_0.<ReadPackageFromUrl>b__0() in D:\home\site\repository\Data\PackageData.cs:line 408
   at System.Threading.Tasks.Task.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__275_1(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at FuGetGallery.PackageData.PackageDataCache.ReadPackageFromUrl(PackageData package, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 408
   at FuGetGallery.PackageData.PackageDataCache.GetValueAsync(String arg0, PackageVersion arg1, HttpClient httpClient, CancellationToken token) in D:\home\site\repository\Data\PackageData.cs:line 381
```

**Comment by bgrainger** [comment]
Can't reproduce with the latest code from https://github.com/bgrainger/FuGetGallery/commits/master; this might have been fixed as the side-effect of fixing another bug (e.g., failure to retrieve all versions).

**Comment by eli-darkly** [comment]
I'm seeing the same thing here: https://www.fuget.org/packages/LaunchDarkly.JsonStream

**Comment by praeclarum** [comment]
Both these packages are working at them moment. Please let me know if they fail again.
